CREATE TABLE IF NOT EXISTS `ad_computers` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ad_dn` VARCHAR(255) NOT NULL UNIQUE,
    `hostname` VARCHAR(255) NOT NULL,
    `os` VARCHAR(255) NULL,
    `last_logon` BIGINT NULL,
    `last_sync` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ad_dn` VARCHAR(255) NOT NULL UNIQUE,
    `samaccountname` VARCHAR(255) NOT NULL,
    `displayname` VARCHAR(255) NULL,
    `last_sync` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_groups` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ad_dn` VARCHAR(255) NOT NULL UNIQUE,
    `cn` VARCHAR(255) NOT NULL,
    `last_sync` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ad_computer_metrics` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `computer_id` INT NOT NULL,
    `cpu_usage` INT NULL,
    `memory_free` BIGINT NULL,
    `disk_free` BIGINT NULL,
    `polled_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`computer_id`) REFERENCES `ad_computers`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;